version: "3.8"

services:
  edgerunner-app:
    build: .
    container_name: edgerunner-app
    ports:
      - "9090:9090"
    volumes:
      - ./data:/app/data
      - puppeteer-cache:/home/pptruser/app/.cache/puppeteer
    env_file:
      - ./env/.env.production
    environment:
      - PUPPETEER_CACHE_DIR=/home/pptruser/app/.cache/puppeteer
    restart: always

volumes:
  puppeteer-cache:

